version: '3.1'

services:
  app:
    container_name: customer-frontend
    image: customer-frontend
    build: 
      context: .
    ports:
      - "4002:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
      - STATUS=prod

networks:
    default:
        external:
            name: testing-nw


