name: docker-compose-actions-workflow

on: 
  push: 
    branches: 
      - main
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: docker-compose up --force-recreate --build --detach
      - name: Prune Docker Images
        run: docker image prune -a -f